//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public long b_id { get; set; }
        public string b_name { get; set; }
        public byte b_dayID { get; set; }
        public byte b_timID { get; set; }
        public int b_facID { get; set; }
        public byte b_status { get; set; }
        public System.DateTime b_startDate { get; set; }
    
        public virtual dayss dayss { get; set; }
        public virtual user user { get; set; }
        public virtual timing timing { get; set; }
    }
}
