//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrollType
    {
        public int et_id { get; set; }
        public string et_name { get; set; }
        public int et_currID { get; set; }
    
        public virtual curriculum curriculum { get; set; }
    }
}
