

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class aptechDBEntities : DbContext
{
    public aptechDBEntities()
        : base("name=aptechDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<batch> batches { get; set; }

    public virtual DbSet<campus> campuses { get; set; }

    public virtual DbSet<curriculum> curricula { get; set; }

    public virtual DbSet<dayss> daysses { get; set; }

    public virtual DbSet<department> departments { get; set; }

    public virtual DbSet<enrollType> enrollTypes { get; set; }

    public virtual DbSet<role> roles { get; set; }

    public virtual DbSet<semester> semesters { get; set; }

    public virtual DbSet<timing> timings { get; set; }

    public virtual DbSet<user> users { get; set; }

    public virtual DbSet<coursesOffered> coursesOffereds { get; set; }

    public virtual DbSet<mediaFormat> mediaFormats { get; set; }

    public virtual DbSet<walkin> walkins { get; set; }


    public virtual ObjectResult<st_getLoginDetails_Result> st_getLoginDetails(string user, string pass)
    {

        var userParameter = user != null ?
            new ObjectParameter("user", user) :
            new ObjectParameter("user", typeof(string));


        var passParameter = pass != null ?
            new ObjectParameter("pass", pass) :
            new ObjectParameter("pass", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_getLoginDetails_Result>("st_getLoginDetails", userParameter, passParameter);
    }


    public virtual ObjectResult<Nullable<int>> st_getCampusCount()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("st_getCampusCount");
    }


    public virtual ObjectResult<st_getTodaysWalkins_Result1> st_getTodaysWalkins(Nullable<int> day, Nullable<int> month, Nullable<int> year, Nullable<int> userID)
    {

        var dayParameter = day.HasValue ?
            new ObjectParameter("day", day) :
            new ObjectParameter("day", typeof(int));


        var monthParameter = month.HasValue ?
            new ObjectParameter("month", month) :
            new ObjectParameter("month", typeof(int));


        var yearParameter = year.HasValue ?
            new ObjectParameter("year", year) :
            new ObjectParameter("year", typeof(int));


        var userIDParameter = userID.HasValue ?
            new ObjectParameter("userID", userID) :
            new ObjectParameter("userID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_getTodaysWalkins_Result1>("st_getTodaysWalkins", dayParameter, monthParameter, yearParameter, userIDParameter);
    }

}

}

