//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    
    public partial class st_getTodaysWalkins_Result1
    {
        public long WalkinID { get; set; }
        public string Fullname { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
    }
}
