//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.batches = new HashSet<batch>();
            this.walkins = new HashSet<walkin>();
        }
    
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string u_username { get; set; }
        public string u_pass { get; set; }
        public string u_phone { get; set; }
        public string u_email { get; set; }
        public int u_roleID { get; set; }
        public int u_departID { get; set; }
        public string u_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch> batches { get; set; }
        public virtual department department { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<walkin> walkins { get; set; }
    }
}
