
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4
{

using System;
    using System.Collections.Generic;
    
public partial class walkin
{

    public long w_id { get; set; }

    public System.DateTime w_datetime { get; set; }

    public string w_fullname { get; set; }

    public string w_phone1 { get; set; }

    public string w_phone2 { get; set; }

    public string w_email { get; set; }

    public Nullable<System.DateTime> w_dob { get; set; }

    public int w_coID { get; set; }

    public int w_mfID { get; set; }

    public int w_userID { get; set; }

    public string w_serialNo { get; set; }

    public byte w_isAdmissionTaken { get; set; }



    public virtual coursesOffered coursesOffered { get; set; }

    public virtual mediaFormat mediaFormat { get; set; }

    public virtual user user { get; set; }

}

}
